"""Add the user_id field to reservation model

Revision ID: 60363d3939b1
Revises: c3ab97e46a01
Create Date: 2024-09-19 17:05:47.572633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60363d3939b1'
down_revision = 'c3ab97e46a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservationmodel', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_reservationmodel_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservationmodel', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservationmodel_user_id_user', type_='foreignkey')

    # ### end Alembic commands ###
